"""added quantity to table

Revision ID: 485bacb13af3
Revises: 1df5bad215a6
Create Date: 2024-11-25 15:09:57.381041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485bacb13af3'
down_revision = '1df5bad215a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
