"""debugging seed.py

Revision ID: 668c337e0bc6
Revises: 485bacb13af3
Create Date: 2024-11-26 14:38:03.564695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668c337e0bc6'
down_revision = '485bacb13af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_order_product', ['order_id', 'product_id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('order_total',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_total',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.drop_constraint('uix_order_product', type_='unique')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
