"""testing no password app to debug

Revision ID: d363e2203bc6
Revises: 0133a7a1b42e
Create Date: 2024-12-06 09:40:02.500873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd363e2203bc6'
down_revision = '0133a7a1b42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customers_username', type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.create_unique_constraint('uq_customers_username', ['username'])

    # ### end Alembic commands ###
